### ISSUE TITLE
AH-64D Plt L Panel Throttle Lever - Cut Off to Idle - Switch

### ISSUE THREAD

**Issue by Petedcc** [DCS-Skunkworks/dcs-bios#999] opened 2024-08-25 14:30 UTC
### Version

- [x] I am using the latest version

### Aircraft

AH-64D

### Control

PLT L Console

### Description

Currently there is only the smooth motion for potentiometers on the power levers. This only works from idle to full power. the levers need a switch input to move from cut off to idle.
In the screenshots ive labelled the relevant controls ABCD.
Without a keyboard or joystick bind input it is impossible to use the power levers from startup as you cant click and drag them in the cockpit.

### Screenshots

![Uploading control-setup.PNG…](
![throttle1](https://github.com/user-attachments/assets/2e8894b6-7417-47d4-bbaa-fada8ba7a396)
![throttle2](https://github.com/user-attachments/assets/435fe840-3cdb-46f0-affd-6d7166896932)
)
![control-setup](https://github.com/user-attachments/assets/16ef4b71-5cc8-4100-8b1c-a2f51e9bc8ad)

**Comment by charliefoxtwo** [comment] 2024-08-25 21:40
Looks like this is doable from the pilot seat, however the controls don't seem to work from the copilot seat - not clear why.

**Comment by Petedcc** [comment] 2024-08-25 21:43
Thanks for looking into this. That shouldnt be an issue. Only really used on engine start/shutdown which would be done from pilot seat anyway.

**Comment by charliefoxtwo** [comment] 2024-08-25 21:54
Ok, I've added the following controls:
- `PLT_ENG_L_PW_LVR_LIFT` - set to 1 to activate finger lift, 0 to deactivate - used for accessing Lock Out position
- `PLT_ENG_R_PW_LVR_LIFT` - set to 1 to activate finger lift, 0 to deactivate - used for accessing Lock Out position
- `PLT_ENG_L_PW_LVR_IDLE` - trigger to move to idle
- `PLT_ENG_R_PW_LVR_IDLE` - trigger to move to idle
- `PLT_ENG_L_PW_LVR_OFF` - trigger to move to off
- `PLT_ENG_R_PW_LVR_OFF` - trigger to move to off

Due to module limitations, none of these controls have any output.

**Comment by charliefoxtwo** [comment] 2024-08-25 21:57
A new nightly build should be released in 10-15 minutes - give it a try and let me know if it works.

**Comment by Petedcc** [comment] 2024-08-25 21:58
Thankyou ver much for that, il have to try it tomorrow now but I shall report back. 
I'm not sure why the finger lift is there, doesn't seem to have any fuction. And yes that was my issue, the potentiometer won't work untill the lever is set to idle. Strange logic!
Thanks again.

**Comment by charliefoxtwo** [comment] 2024-08-25 23:02
The finger lift does have a function - it must be actioned in order to set the throttle to lockout (which is at the top of the range - I have no idea what the actual function of that position is)

**Comment by Petedcc** [comment] 2024-08-26 09:40
Hi Charlie, those new refs do work thanks, but is it possible to make 1 ref as a toggle so idle when pressed, off when release rather than needing 2 separate switches/buttons?

**Comment by charliefoxtwo** [comment] 2024-08-26 14:10
The problem is that there is no way of knowing what state the game is in. I don't know how Switch2Pos works (I'm not familiar with the arduino code) but I could maybe do something similar to what I did with the finger lifts - but it would be just like the finger lifts in that you could set the state to 1 or 0, but inc/dec and toggle wouldn't work.

**Comment by Petedcc** [comment] 2024-08-26 14:19
Yes thats exactly what im after, setting the state 0 or 1.
Im building the trottle and the idea is to have a micro switch so when the lever is back the switch is pressed and asigns cutoff, then when moved to idle, the switch is released assigning idle

**Comment by Petedcc** [comment] 2024-09-02 15:05
Hi Charlie, any luck in getting the power levers to set a position instead of toggling yet?

**Comment by charliefoxtwo** [comment] 2024-09-02 15:14
Been swamped with other projects so haven't had time to work on dcs-bios lately. I'll see if I can get it in the nightly build today.

**Comment by charliefoxtwo** [comment] 2024-09-02 15:35
I mean it's something anyone can submit a pull request for, but it's not a one-line change if that's what you're asking. The way this control works is special, so we don't have toggle-switch controls for controls like this anywhere in bios. We didn't have a way to manipulate them at all until the last commit I pushed for this issue.

**Comment by Petedcc** [comment] 2024-09-02 15:38
Ah right I see, I dont know much about the workings of bios yet, I shall leave it in your hands, if you cant get it done then no rush, would just be useful Appreciate your help with it!

**Closed** 2024-09-02 16:01 UTC
Labels: enhancement
