### ISSUE TITLE
F-16 F-16C_50/ANTI_SKID_SW logic error when changing states

### ISSUE THREAD

**Issue by spec10** [DCS-Skunkworks/dcs-bios#490] opened 2023-11-06 14:48 UTC
It seems like something's wrong with ANTI_SKID_SW. If you switch it to position 2 (Parking Brake) and then send 0 (off) it will move to 1 (Anti-Skid). Reproducable in bort.

**Comment by jdahlblom** [comment] 2024-01-01 10:07
If I have it in Parking (2) and click with the mouse to move it it moves to Anti Skid (1), if I click again it goes to Off (0). I can only see that dcs-bios is following that behavior.  I am using ctrlref.exe, not BORT.
This is one of the types of controls that have 2 different commands so it is not that straightforward manipulating it.
```
		if toState == "0" then --downSwitch
			dev:performClickableAction(down_switch, 0)
			dev:performClickableAction(up_switch, 0)
			dev:performClickableAction(down_switch, -1)
		elseif toState == "1" then --Stop
			dev:performClickableAction(down_switch, 0)
			dev:performClickableAction(up_switch, 0)
		elseif toState == "2" then --upSwitch
			dev:performClickableAction(down_switch, 0)
			dev:performClickableAction(up_switch, 0)
			dev:performClickableAction(up_switch, 1)
		end
```

There you can see that there are the commands ```up_switch``` and ```down_switch```.

**Comment by charliefoxtwo** [comment] 2024-01-01 16:38
I believe the issue is regarding having the switch in parking and then sending set_state 0, which should move it immediately to off, but it sounds like it goes to the middle position instead.

Controls like these can be tough to get right. Sometimes the module just doesn't play nice - it's pretty annoying. Unfortunately I don't have the F-16 so I'm not able to experiment.

**Comment by charliefoxtwo** [comment] 2024-07-07 18:22
Alright, I was able to figure out a workaround - this should be fixed in the next build!

**Closed** 2024-07-07 18:26 UTC
Labels: bug in BIOS
