### ISSUE TITLE
[BUG] F-15E: Some RICP switches not working

### ISSUE THREAD

**Issue by rocketeer998** [DCS-Skunkworks/dcs-bios#530] opened 2024-02-18 03:09 UTC
**DCS-BIOS version**
latest version. downloaded 2 days ago.

**DCS-BIOS Control**
Remote Intercommunications Control Panel 
The following switches have stopped working. Used to work in the past.

//Front WPN Volume
DcsBios::RotaryEncoder fVolWpn("F_VOL_WPN", "-3200", "+3200", 39, 40);

//Front MICS Crypto Switch
DcsBios::Switch3Pos fRCypTxt("F_MIC_CRYPT", 45, 46);

//Front Radio Cypher Text Switch
DcsBios::Switch2Pos fMicCrypt("F_R_CYP_TXT", 53);

//Front IFF Mode Switch
DcsBios::Switch3Pos fIffMode("F_IFF_MODE", A1, A2);

//Front IFF Reply Switch
DcsBios::Switch3Pos fIffReply("F_IFF_REPLY", A3, A4);

//Front IFF Master Switch
DcsBios::Switch3Pos fIffMaster("F_IFF_MASTER", A5, A6);

**Describe the bug**
see attached pictures. I use a DCS BIOS debug tool. The above all will generate the switch name when it is turned. But none of these move in DCS game. All other switches in this Remote Intercommunications Control Panel are working.

**To Reproduce**
Steps to reproduce the behavior example:
1. Start A-10C mission
2. Send ```FLAPS_SWITCH INC``` to dcs-bios
3. Nothing happens

**Expected behavior**

**Screenshots**
![test1](https://github.com/DCS-Skunkworks/dcs-bios/assets/145094080/37a2e2fb-8446-4dc7-b75c-d7833cff24c9)
![test2](https://github.com/DCS-Skunkworks/dcs-bios/assets/145094080/570b7a86-d098-4f55-aad5-f5fa77ba1d5b).

**Additional context**

**Comment by charliefoxtwo** [comment] 2024-02-18 15:07
I'm not familiar with that debug tool. Have you tried with [Bort](https://github.com/DCS-Skunkworks/Bort)?

**Comment by rocketeer998** [comment] 2024-02-18 21:46
no. but regardless of whichever tool you use, it proves that when pressed, it triggers some value, with the correct name of the switch each time and not just some random data. that proves that those switches are indeed trying to trigger the values that they have been coded for. But in DCS it's not transferred to the virtual switches in the game. so something in dcs bios is not working for these stated switches.

**Comment by charliefoxtwo** [comment] 2024-02-18 23:45
As I don't know anything about that debug tool, unfortunately it doesn't prove anything to me. I have no idea how or whether that debug tool works and I can't guarantee its functionality (of course I can't guarantee Bort's functionality either, but at least if Bort is broken then it's my problem 😆).

Is it just those switched you mentioned? Do other switches continue to work (including other switches on that panel, as well as on different panels)?

**Comment by rocketeer998** [comment] 2024-02-19 02:16
Like I said above, the debug tool doesn't spit out random stuff. When you press a switch, it shows the correct switch name assigned to it. everytime. whether it works in dcs or not, the debug tools shows the correct switch name. so to me it works.

I've separated panels into different bug post. This post is about the RICP panel. Bug 525 about CAS. Bug 528 about Engine panel.

I haven't tried Bort. Are you saying if it works in Bort it will work in DCS? When I reported LEDs not working for AMAD panel (bug 223), warlord says it works in bort, but I found it still doesn't work in dcs, which is the ultimate test. If you guys provide support for the dcs bios, you should have access to the dcs aircraft modules that the code covers and not just trust the result of bort, coz dcs is where everyone plays and know first hand if things work or not.

**Comment by charliefoxtwo** [comment] 2024-02-19 05:25
What do you mean by "whether it works in dcs or not"? Maybe I'm not following, but how would an output not work in DCS but work in any other tool? 

Again, I can't really help debug any behavior with any other tools. I can really only help with our own tools. I haven't had the time to launch dcs and test for myself yet.

**Comment by rocketeer998** [comment] 2024-02-19 21:48
so we use different debug tool. I use the tool by the guy called Quick. You use Bort. But the ultimate test is DCS game itself. Even if all switches in working in both yours and my debug tools, if they don't work in DCS then something still needs to be fixed.

**Comment by charliefoxtwo** [comment] 2024-02-19 22:34
We must be talking about different things here - how would something work in a debug tool like bort but not work in dcs?

The reason I'm asking you to test in bort is because we (DCS-Skunkworks) are also responsible for bort. That means if something isn't working, we at least can be confident it's our problem. If you're experiencing issues with some other tool, I can't be confident whether the issue is with bios or with that tool without testing myself. That's not always possible - we don't all own all the modules, and even for modules we do own we may not have a good understanding of how the controls should work. As an example, while I do own the A-10C II I have no idea where the "Remote Intercommunications Control Panel" is located within the aircraft.

Separate question: you mentioned in your initial post that this is with the A-10C. Are you referring to the original A-10C, or the A-10C II Tank Killer?

**Comment by rocketeer998** [comment] 2024-02-20 18:10
All the issues reported recently, the RICP (Remote Intercommunications Control Panel), CAS, Engine panels etc are for the F-15E.

**Comment by charliefoxtwo** [comment] 2024-02-20 20:42
Ok, I've updated the title to better reflect the issue. However, as I don't own the F-15 if you're not willing to test with Bort there's not a lot I can do to help you.

@jdahlblom is this something you would be able to test?

**Comment by rocketeer998** [comment] 2024-02-20 20:52
I can go figure out how to use Bort. But once again, the ultimate test is the DCS game itself. This is what dcs bios is written for. Whatever tools we use to test, they are just a tool. If it does not work in DCS but something is still wrong.

You guys reported LEDs working for the F-15E AMAD panel in #223 according to Bort. But I retested them several times in DCS and they still don't work. Hence my skepticism in relying on Bort to tell me if things are working or not.

**Comment by charliefoxtwo** [comment] 2024-02-20 22:55
If bort says an LED is on, it's because the address bios is querying from DCS is sending a value indicating it's on. It's possible that bios is polling the wrong data which would indicate a bug in bios, however bort only displays what bios sends it and I'm very confident in that behavior. If there is a bug in bios that results in one control querying incorrect data in DCS, then bort will display that data because that's what it's sent from bios.

Inputs are similar. However, you can also use bort to send values to bios. If you test flipping a switch in bort and observe it does not change position in dcs, that to me would generally indicate a bug in bios. However I can't draw the same conclusion for any other debug tool because I cannot be equally confident in their behavior.

**Comment by jdahlblom** [comment] 2024-02-21 08:07
> Ok, I've updated the title to better reflect the issue. However, as I don't own the F-15 if you're not willing to test with Bort there's not a lot I can do to help you.
> 
> @jdahlblom is this something you would be able to test?

Yes I can test

**Comment by jdahlblom** [comment] 2024-02-21 15:45
Quick test with my simple Arduino setup. Both of these works just fine. `UNO R3`
```
DcsBios::Switch3Pos fIffMode("F_IFF_MODE", leftSwitch, rightSwitch);
DcsBios::Switch2Pos fMicCrypt("F_R_CYP_TXT", leftSwitch);
```

**Comment by rocketeer998** [comment] 2024-02-21 19:03
where do you get this data broker thing above? I downloaded bort latest version, and all I see is this.
![bort](https://github.com/DCS-Skunkworks/dcs-bios/assets/145094080/303cd123-7b66-440e-8039-5c0754a07281)

Even all the people on youtube showing steps to install dcs bios that include bort, they just copy its code to paste into arduino, very much the same as me copying code from the control-reference.html from browser.

So once a certain com port that is connected is detected by this tool above and all switches that are properly wired will show up green? then we conclude they are working? how do you jump from the code you want to test to the screen above?

**Comment by jdahlblom** [comment] 2024-02-21 19:13
The data broker is a new tool I wrote. It hasn't been released yet but I
used it when verifying whether the above two switches worked from Arduino.
The broker got the dcs-bios commands from Arduino and sent them to
dcs-bios. And the changes showed in DCS & ctrlref.

Den ons 21 feb. 2024 21:03rocketeer998 ***@***.***> skrev:

**Comment by rocketeer998** [comment] 2024-02-21 19:44
so at the moment, without this data broker tool, all Bort is to us in the public is another way to grab the dcs bios code, like the control reference html. nothing more. you have been saying you guys use bort to test and all I've seen so far in Bort is a bunch of code, couldn't figure out how to use it to test. now I understand. you guys were using another tool, not bort itself as it can't do any test. there is no live connection to any com port for testing.

**Comment by jdahlblom** [comment] 2024-02-21 20:11
No no no.
With bort you will see if a change happens in DCS. No cockpit control can change without bort seeing the change.

**Comment by rocketeer998** [comment] 2024-02-21 22:54
ok i scrolled down and saw bort output changes when flipping toggles when dcs is running. So I tested the code below again for the F-15E's RICP panel.

//Front WPN Volume
DcsBios::RotaryEncoder fVolWpn("F_VOL_WPN", "-3200", "+3200", 39, 40);

//Front MICS Crypto Switch
DcsBios::Switch3Pos fRCypTxt("F_MIC_CRYPT", 45, 46);

//Front Radio Cypher Text Switch
DcsBios::Switch2Pos fMicCrypt("F_R_CYP_TXT", 53);

//Front IFF Mode Switch
DcsBios::Switch3Pos fIffMode("F_IFF_MODE", A1, A2);

//Front IFF Reply Switch
DcsBios::Switch3Pos fIffReply("F_IFF_REPLY", A3, A4);

//Front IFF Master Switch
DcsBios::Switch3Pos fIffMaster("F_IFF_MASTER", A5, A6);


I used different physical switch, different arduino mega, different com port. in case the existing wiring has problems. 
Tested with a known switch, proved that it works in DCS and bort output showed changes.
then tested all these above. All didn't move in DCS and bort output showed no change.

swapped to other pins in the mega. same thing. not working.

**Comment by charliefoxtwo** [comment] 2024-02-21 23:23
Thanks. Did you also test the bort input for these switches to see if it changes the model in-game, and if the model changes in-game are reflected in bort? This way we can isolate if this is a bios problem or an arduino problem. Basically if you're able to toggle the one of the problem switches in bort and it works correctly in dcs (and if likewise toggling the switch in-game shows the correct value in bort), then we have an interesting arduino problem. On the other hand, if the bort inputs don't work for these problem switches and if flipping these switches in-game is not accurately reflected in bort, then we have an issue with the switch definitions in bios.

**Comment by rocketeer998** [comment] 2024-02-21 23:35
i tested both at the same time, dcs in game and bort. when a switch is working,  both in dcs game and bort will show movement/changes. when a switch doesn't work, both don't work. they are consistent. so this panel alone, the ones i listed are not working both in game and bort. all others that work in game also show output changes in bort. at least this is consistent.

**Comment by charliefoxtwo** [comment] 2024-02-22 00:22
I'm sorry, I still don't understand what you mean when you say a switch doesn't work in-game. Like, you're clicking on it in-game and it doesn't move?

**Comment by rocketeer998** [comment] 2024-02-22 01:15
as in flipping a physical toggle and it doesn't do the same in the game.

**Comment by charliefoxtwo** [comment] 2024-02-22 05:28
Ok but to be clear, when testing the output you're testing these switches by actually clicking them with your mouse in-game, not by using your arduino, bort, or anything else, right?

**Comment by rocketeer998** [comment] 2024-02-22 20:41
No. There is no point clicking the switches in the game with the mouse. The purpose of dcs bios is to mimick the actual switches, so that when one flips a real switch, the same switch in the game flips too. so arduino is to make dcs game mirror the real thing. clicking in the game will work in making the switches in dcs flip. the mouse click will also make bort change value. but the physical switch is not able to change the switch in the game or bort. 

the same switch when rewired to other switches will work. so the wiring, arduino etc are done correctly. but certain switches just refuse to work while others work fine.

when a physical switch can flip toggle in dcs game, it will also change the output in bort. when it does not do so for the game, then it doesn't do anything to bort too.

**Comment by rocketeer998** [comment] 2024-02-23 04:38
I downloaded the one that says Code in top right of the fork page. not the one that says latest release stable update 2.8.7.
How do you get the open beta version? I assume the zip I download from the code button is the stable update version?

![Capture](https://github.com/DCS-Skunkworks/dcs-bios/assets/145094080/a3248193-62fe-442c-ac80-e0cecdd0f82f)

For testing bort, you have the INC DEC buttons, second part is the interface: set_state slider 0 to 2. Third is the output below.
1. Clicking on INC DEC doesn't do anything to set_state slider or output.

2. Clicking and dragging the slider left and right doesn't change output either

3. Clicking on the IFF Mode toggle in the game does change the output from 0 to 1 to 2 etc. But doesn't change the set state value or slider

I feel that INC DEC buttons are meant for encoders only. This is a toggle. The default code is RotaryEncoder at the top.

Then 4 lines of code for multipos, switch3pos, matrix3pos and analogmultipos.
To me the code that makes sense for this 3 way toggle is the switch3pos one.
maybe that should be the default at the top? maybe physical switches are forced to interface with the default encoder code which doesn't match its switch type a 3 position toggle?

Nevermind. I see all toggles have encoder as the default top line, even for those working ones, even for known push buttons. I wonder why.

**Comment by charliefoxtwo** [comment] 2024-02-23 05:34
You can download the openbeta release by clicking on [Releases](https://github.com/DCS-Skunkworks/dcs-bios/releases). Downloading via clicking the code dropdown is fine too.

INC/DEC is not just meant for encoders. For a toggle switch, they _should_ move the switch up and down.

Thanks for running those tests. This tells me that bios isn't processing the input correctly, but at least we do have the control address correct. A note about the slider though - after dragging it, you have to click the button below to actually set the value. Could you try that? Sometimes some inputs work, but not others, so it's good to test all supported inputs.

Just a note, clicking the switch in game is not supposed to adjust the set state value or slider - just the output, so that behavior would be expected.

Many switches support multiple input types. You could also experiment with the different input types in your arduino and see if any of them work. That would also provide helpful information if you're able to get one of them to work.

@jdahlblom, when you were testing with broker, were you testing inputs or just outputs? If you were testing inputs, which inputs did you test?

**Comment by jdahlblom** [comment] 2024-02-23 08:19
@charliefoxtwo  I did outputs only. I can test the inputs.

**Comment by rocketeer998** [comment] 2024-02-24 06:59
So I clicked on the slider then click on the box below. Didn't change anything to the output. Clicking on INC and DEC didn't do anything too to the output, nor did it move any switch. I tested these for the MODE, REPLY and MASTER switches in the IFF.

Mouse clicking on the switches still change output in bort. but only this and nothing else will change output.

**Comment by jdahlblom** [comment] 2024-02-24 07:58
Did this test on my test bench and it worked. This uses input from dcs-bios.
```
static int leftSwitch = 13;
static int rightSwitch = 12;

static int redLed = 5;
static int greenLed = 6;
static int yellowLed = 7;
//DDRD = 0XFF;
//PORTD = 0XFF;

DcsBios::Switch3Pos fIffMode("F_IFF_MODE", leftSwitch, rightSwitch);
//DcsBios::Switch2Pos fMicCrypt("F_R_CYP_TXT", leftSwitch);
//DcsBios::Switch3Pos fireTestSw("FIRE_TEST_SW", leftSwitch, rightSwitch);

void onFIffModeChange(unsigned int newValue) 
{
    switch(newValue)
    {
      case 0 : 
        PORTD |= (1<<PD7);
        PORTD &= ~(1<<PD6);
        PORTD &= ~(1<<PD5);
        break;
      case 1 : 
        PORTD &= ~(1<<PD7);
        PORTD |= (1<<PD6);
        PORTD &= ~(1<<PD5);
        break;
      case 2 : 
        PORTD &= ~(1<<PD7);
        PORTD &= ~(1<<PD6);
        PORTD |= (1<<PD5);
        break;
      default :
        break;
    }
    
    //PORTD |= (1<<PD7);
}
DcsBios::IntegerBuffer fIffModeBuffer(0x93d2, 0x0300, 8, onFIffModeChange);

void setup() {
  DcsBios::setup();  
}

void loop() {
  DcsBios::loop();
}
```

**Comment by jdahlblom** [comment] 2024-02-24 14:27
> So I clicked on the slider then click on the box below. Didn't change anything to the output. Clicking on INC and DEC didn't do anything too to the output, nor did it move any switch. I tested these for the MODE, REPLY and MASTER switches in the IFF.
> 
> Mouse clicking on the switches still change output in bort. but only this and nothing else will change output.

You have something wrong in your setup. I just tried both ctrlref and Bort, both works with these switches. You might want to check the wiki troubleshooting pages.

**Comment by jdahlblom** [comment] 2024-03-07 13:38
Where are we with this issue?

**Comment by rocketeer998** [comment] 2024-03-07 19:27
Using the latest dcs bios version, there is no change to the code for these switches below but they are now working in the game.
//Front WPN Volume
DcsBios::RotaryEncoder fVolWpn("F_VOL_WPN", "-3200", "+3200", 39, 40);

//Front IFF Mode Switch
DcsBios::Switch3Pos fIffMode("F_IFF_MODE", A1, A2);

//Front IFF Reply Switch
DcsBios::Switch3Pos fIffReply("F_IFF_REPLY", A3, A4);

//Front IFF Master Switch
DcsBios::Switch3Pos fIffMaster("F_IFF_MASTER", A5, A6);

**Comment by rocketeer998** [comment] 2024-03-07 19:33
For these two switches, the first line is old code. second line the new code. Looks like the first part of the code got switched between them.

//Front MICS Crypto Switch
//DcsBios::Switch3Pos fRCypTxt("F_MIC_CRYPT", 45, 46);
DcsBios::Switch3Pos fMicCrypt("F_MIC_CRYPT", 45, 46);  

//Front Radio Cypher Text Switch
//DcsBios::Switch2Pos fMicCrypt("F_R_CYP_TXT", 53);
DcsBios::Switch2Pos fRCypTxt("F_R_CYP_TXT", 53);  

The 2 position toggle cypher text switch is now working.
The 3 position toggle crypto switch is not working coz it is not moving in dcs too. strange. even mouse click in the game does nothing. the toggle is just frozen.

so now all switches on the RICP panel is working except this crypto switch.

**Comment by jdahlblom** [comment] 2024-03-08 06:33
```userguide.html```:

![macros](https://github.com/DCS-Skunkworks/dcs-bios/assets/10453261/1afa636d-03cd-4921-bc7d-134d408d202c)

**Comment by jdahlblom** [comment] 2024-03-08 06:34
Problem(s) solved, closing issue.

**Closed by jdahlblom** 2024-03-08 06:34 UTC
Labels: user setup problems
